select * from customer
-- Q1. what is the total revenue generated by male vs. female customers
select gender, sum(purchase_amount) from customer
group by gender
order by sum(purchase_amount) desc

--Q2 which customer used a discount but still spent more than the average purchase amount?
SELECT *
FROM customer
WHERE "discount_applied" = 'Yes'
AND "purchase_amount" >
(
    SELECT AVG("purchase_amount")
    FROM customer
);

--Q3 which are the top 5 products with the highest average review rating?
select item_purchased, avg(review_rating) from customer
group by item_purchased
order by avg(review_rating) desc limit 5

-- Q4 Compare the avg purchase amounts between standard and express shipping
select shipping_type, round(avg(purchase_amount),2) from customer
where shipping_type in ('Standard','Express')
group by shipping_type

-- Q5 do subscribed customers spend more? compare avg spend and total revenue between subscribers and non-subscribers
SELECT 
    subscription_status,
    COUNT(DISTINCT customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Q6 which 5 products have the highest percentage of puchases with discounts applied 
SELECT 
    item_purchased,
    COUNT(*) AS total_purchases,
    
    SUM(
        CASE 
            WHEN discount_applied = 'Yes' THEN 1
            ELSE 0
        END
    ) AS discounted_purchases,

    ROUND(
        100.0 * SUM(
            CASE 
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS discount_percentage

FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7 segment customer into new, returning , and loyal based on thier total number of previous purchases and show the count of each segment
SELECT 
    customer_segment,
    COUNT(*) AS customer_count
FROM
(
    SELECT 
        customer_id,
        previous_purchases,

        CASE
            WHEN previous_purchases <= 5 THEN 'New'
            WHEN previous_purchases BETWEEN 6 AND 15 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment

    FROM customer
) AS segmented_customers

GROUP BY customer_segment
ORDER BY customer_count DESC;

-- Q8 what are the top 3 most purchased products within each category
SELECT 
    category,
    item_purchased,
    total_purchases
FROM
(
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,

        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rank

    FROM customer
    GROUP BY category, item_purchased
) ranked_products

WHERE rank <= 3
ORDER BY category, total_purchases DESC;

-- Q9 are customers who are repeat buyers (more than 5 previous puchases) also likely to subscribe
SELECT 
    subscription_status,
    COUNT(*) AS customer_count
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10 what is the revenue contribution of each age group
select age_group,sum(purchase_amount) from customer
group by age_group

select * from customer





























































